### ISSUE TITLE
Energy too low for the Leap Motion

### ISSUE THREAD

**Issue by cerkut** [bcaramiaux/Gestural-Sound-Toolkit#1]
Thanks for the great toolbox. I am not sure if the GST is calibrated to wax, Leap Motion results in too low Energy values. A simple solution is to multiply the Energy output value with [\* 25.] but there is clipping in the Energy block and we'll loose resolution like this. How do you work with Leap Motion?

**Comment by bcaramiaux** [comment]
Thanks @cerkut for trying it out! It seems that your problem is due to the object [clip 0. 1.] in the patch computing the energy as the leap motion outputs values much higher than 1. I pushed a version bypassing the [clip] object. Let me know if you still have an issue with it.

**Comment by cerkut** [comment]
Thanks, Leap Motion Energy works beautifully now :-) I can detect Kick and trigger samples. Closing the issue, proceeding to GVF trials.
